export const seance_mardi_3_juin = {
  id: "2025-06-03",
  nom: "Récupération active & renfo léger",
  description: "Séance adaptée pour soulager le bras droit, activer le bas du corps et maintenir un bon tonus sans générer de courbatures.",
  duree: 50,
  type: "récupération_active",
  niveau: "léger",
  objectifs: [
    "Soulager l’épaule droite",
    "Activer les jambes et le tronc",
    "Préserver la mobilité sans aggraver les douleurs"
  ],
  exercices: [
    {
      id: "echauffement_marche_place",
      nom: "Marche rapide sur place",
      categorie: "échauffement",
      groupe_musculaire: ["général"],
      duree: 180,
      description: "Marche active sur place en relâchant bien les bras.",
      position_depart: "Debout, bras relâchés",
      erreurs: ["Garde un rythme doux", "Évite de contracter les épaules"],
      focus: ["Mobiliser doucement", "Favoriser la circulation"],
      materiel: [],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "cercles_epaules",
      nom: "Cercles d’épaules avant/arrière",
      categorie: "échauffement",
      groupe_musculaire: ["épaules"],
      duree: 120,
      description: "Fais de petits cercles avec les épaules vers l’avant puis vers l’arrière.",
      position_depart: "Debout, bras le long du corps",
      erreurs: ["Ne lève pas les bras", "Évite de crisper la nuque"],
      focus: ["Échauffer l’articulation", "Détendre les trapèzes"],
      materiel: [],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "genoux_hauts_talons_fesses",
      nom: "Genoux hauts + talons-fesses",
      categorie: "échauffement",
      groupe_musculaire: ["jambes"],
      duree: 180,
      description: "Alterne montée de genoux et talons-fesses de manière dynamique.",
      position_depart: "Debout, bras relâchés",
      erreurs: ["Évite les à-coups", "Garde un rythme fluide"],
      focus: ["Activer jambes et cœur", "Coordination motrice"],
      materiel: [],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "air_squat",
      nom: "Air squat",
      categorie: "renforcement",
      groupe_musculaire: ["jambes", "fessiers"],
      repetitions: [3, 15],
      description: "Effectue des squats sans charge, en contrôlant bien la descente.",
      position_depart: "Debout, pieds largeur épaules",
      erreurs: ["Garde le dos droit", "Évite que les genoux dépassent les orteils"],
      focus: ["Contrôle du mouvement", "Activation fessiers"],
      materiel: [],
      type: "repetitions",
      niveau: "facile"
    },
    {
      id: "fentes_statiques",
      nom: "Fentes statiques alternées",
      categorie: "renforcement",
      groupe_musculaire: ["jambes", "fessiers"],
      repetitions: [3, 10],
      description: "Effectue des fentes avant sans déplacement, en alternant les jambes.",
      position_depart: "Debout, jambes légèrement écartées",
      erreurs: ["Ne laisse pas le genou avant dépasser les orteils", "Garde le dos droit"],
      focus: ["Équilibre", "Stabilité du genou"],
      materiel: [],
      type: "repetitions",
      niveau: "facile"
    },
    {
      id: "planche_avant_bras",
      nom: "Planche sur avant-bras",
      categorie: "renforcement",
      groupe_musculaire: ["tronc"],
      repetitions: [3, 30],
      description: "Tiens la position de planche sur les avant-bras en contractant abdos et fessiers.",
      position_depart: "Au sol, avant-bras au sol, jambes tendues ou sur les genoux",
      erreurs: ["Ne laisse pas tomber le bassin", "Évite de creuser le dos"],
      focus: ["Gainage profond", "Posture neutre"],
      materiel: [],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "gainage_lateral_genoux",
      nom: "Gainage latéral sur les genoux",
      categorie: "renforcement",
      groupe_musculaire: ["tronc", "obliques"],
      repetitions: [2, 20],
      description: "Tiens un gainage latéral avec appui sur les genoux.",
      position_depart: "Allongé sur le côté, appui avant-bras et genoux",
      erreurs: ["Ne laisse pas tomber le bassin", "Garde le buste aligné"],
      focus: ["Stabilité latérale", "Engagement des obliques"],
      materiel: [],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "pont_fessier",
      nom: "Pont fessier au sol",
      categorie: "renforcement",
      groupe_musculaire: ["fessiers", "ischio-jambiers"],
      repetitions: [3, 12],
      description: "Monte les hanches en contractant les fessiers puis redescend lentement.",
      position_depart: "Allongé sur le dos, pieds au sol, genoux fléchis",
      erreurs: ["Évite de cambrer", "Ne pousse pas avec les bras"],
      focus: ["Activation fessiers", "Stabilité bassin"],
      materiel: [],
      type: "repetitions",
      niveau: "facile"
    },
    {
      id: "pendulaire_bras_droit",
      nom: "Pendulaire bras droit",
      categorie: "mobilité",
      groupe_musculaire: ["épaule"],
      duree: 120,
      description: "Penche-toi légèrement en avant et laisse ton bras droit se balancer en petits cercles.",
      position_depart: "Debout, appui main gauche sur un support",
      erreurs: ["Le mouvement doit être passif", "Ne contracte pas l'épaule"],
      focus: ["Détente de l’épaule", "Relâchement articulaire"],
      materiel: [],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "rotation_externe_epaule",
      nom: "Rotation externe bras droit (élastique)",
      categorie: "mobilité",
      groupe_musculaire: ["épaule"],
      repetitions: [3, 10],
      description: "Tire lentement l’élastique en rotation externe, coude plaqué au corps.",
      position_depart: "Debout ou assis, coude plié à 90°, bras le long du corps",
      erreurs: ["Ne lève pas l’épaule", "Ne tends pas complètement le bras"],
      focus: ["Stabilité de la coiffe", "Contrôle du mouvement"],
      materiel: ["élastique"],
      type: "repetitions",
      niveau: "facile"
    },
	{
      id: "etirement_pectoraux_mur",
      nom: "Étirement pectoral au mur",
      categorie: "mobilité",
      groupe_musculaire: ["pectoraux", "épaule"],
      duree: 60,
      description: "Bras tendu contre un mur, tourne légèrement le torse pour étirer la poitrine.",
      position_depart: "Debout, main sur un mur à hauteur d’épaule",
      erreurs: ["Ne force pas l’amplitude", "Garde l’épaule basse"],
      focus: ["Ouverture thoracique", "Détente de l’épaule antérieure"],
      materiel: [],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "etirement_fessier_sol",
      nom: "Étirement fessier au sol (pigeon)",
      categorie: "mobilité",
      groupe_musculaire: ["fessiers"],
      duree: 60,
      description: "Étire les fessiers en plaçant une jambe fléchie devant soi au sol et l’autre tendue derrière.",
      position_depart: "Assis au sol, une jambe repliée devant, l’autre tendue derrière",
      erreurs: ["Ne force pas sur le genou", "Garde le bassin centré"],
      focus: ["Détente fessiers", "Ouverture hanche"],
      materiel: [],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "etirement_quadriceps",
      nom: "Étirement quadriceps debout",
      categorie: "mobilité",
      groupe_musculaire: ["quadriceps"],
      duree: 60,
      description: "Attrape la cheville d’une jambe et ramène le talon vers la fesse en gardant les genoux côte à côte.",
      position_depart: "Debout, pied attrapé par la main du même côté",
      erreurs: ["Ne cambre pas le dos", "Garde les genoux alignés"],
      focus: ["Souplesse avant de cuisse", "Posture équilibrée"],
      materiel: [],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "auto_massage_epaule",
      nom: "Auto-massage épaule bras droit",
      categorie: "récupération",
      groupe_musculaire: ["épaule"],
      duree: 180,
      description: "Utilise un rouleau ou un pistolet pour masser doucement l’épaule droite en mouvements circulaires.",
      position_depart: "Debout ou assis, outil en main ou contre un mur",
      erreurs: ["Ne reste pas trop longtemps sur un point douloureux", "N'appuie pas trop fort"],
      focus: ["Relâchement musculaire", "Amélioration de la circulation locale"],
      materiel: ["balle", "rouleau", "pistolet"],
      type: "temps",
      niveau: "facile"
    },
    {
      id: "auto_massage_jambes",
      nom: "Auto-massage jambes rouleau",
      categorie: "récupération",
      groupe_musculaire: ["quadriceps", "ischio-jambiers", "mollets"],
      duree: 300,
      description: "Masse les jambes lentement avec un rouleau sur les principaux groupes musculaires.",
      position_depart: "Assis ou en appui au sol, rouleau sous la jambe",
      erreurs: ["N’appuie pas excessivement", "Reste fluide dans le mouvement"],
      focus: ["Décongestion musculaire", "Récupération active"],
      materiel: ["rouleau"],
      type: "temps",
      niveau: "facile"
    }
  ]
};
